const websites = {
    nl: [`https://nu.nl`,
        `https://telegraaf.nl`,
        `https://ad.nl`,
        `https://NOS.nl`,
        `https://rtlnieuws.nl`,
        `https://volkskrant.nl`,
        `https://geenstijl.nl`,
        `https://nrc.nl`,
        `https://metronieuws.nl`,
    ],
    gb: [],
    us: [],
    fr: [],
    ro: [],
    es: [],
    it: [],
    de: [],
    be: [],
}